# Generated by Django 3.1.7 on 2021-06-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbcville', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField(max_length=50)),
                ('is_owner', models.BooleanField()),
                ('edit_permission', models.BooleanField()),
                ('create_permission', models.BooleanField()),
                ('delete_permission', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Climber',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField(max_length=50)),
                ('c_experience_level', models.PositiveIntegerField()),
                ('routes_attempted', models.PositiveIntegerField()),
                ('is_team_member', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('approach_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('r_type', models.CharField(max_length=20)),
                ('rs_grade', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Route_Log_Entry',
            fields=[
                ('entry_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('beta', models.TextField()),
                ('c_grade', models.CharField(max_length=10)),
                ('c_rating', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Route_Setter',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField(max_length=50)),
                ('rs_experience_level', models.PositiveIntegerField()),
                ('certifications', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
