# Generated by Django 3.1.7 on 2021-06-12 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbcville', '0003_auto_20210611_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='climbcville.location'),
        ),
    ]
