# Generated by Django 3.1.7 on 2021-06-12 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbcville', '0004_route_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='route_log_entry',
            name='route_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='climbcville.route'),
        ),
        migrations.AddField(
            model_name='route_log_entry',
            name='rs_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='climbcville.route_setter'),
        ),
    ]
