# Generated by Django 3.1.7 on 2021-06-12 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbcville', '0005_auto_20210611_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='person_id',
            field=models.ManyToManyField(to='climbcville.Route_Setter'),
        ),
        migrations.AlterField(
            model_name='route_log_entry',
            name='rs_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='climbcville.climber'),
        ),
    ]
