# Generated by Django 3.1.7 on 2021-06-12 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbcville', '0006_auto_20210611_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route_log_entry',
            old_name='rs_id',
            new_name='c_id',
        ),
    ]
