# Generated by Django 3.1.7 on 2021-06-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbcville', '0007_auto_20210611_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='name',
            new_name='route_name',
        ),
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
