# Generated by Django 3.1.7 on 2021-06-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbcville', '0008_auto_20210612_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Input',
            fields=[
                ('location_id', models.IntegerField()),
                ('route_id', models.IntegerField()),
                ('user_code', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
